#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/whichlicense/.github.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Maven Publishing

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: whichlicense/.github/.github/workflows/maven-publishing.yml@main
    with:
      root-directory: ./
    secrets: inherit
