#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/whichlicense/.github.
#
# SPDX-License-Identifier: Apache-2.0
#
name: MoSCoW Prioritization

on:
  pull_request_target:
    types: [ labeled, opened, unlabeled, reopened ]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  check:
    uses: whichlicense/.github/.github/workflows/moscow.yml@main
