#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/whichlicense/.github.
#
# SPDX-License-Identifier: Apache-2.0
#
name: MoSCoW Prioritization

on:
  workflow_call:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: grevend/moscow-prioritization@v2.0.1
