name: Testing

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      distribution:
        type: string
        required: true
      compilation:
        type: string
        required: true
      os:
        type: string
        required: true
      directory:
        type: string
        required: true

jobs:
  test:
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        if: (!contains(inputs.compilation, 'aot') && !contains(inputs.distribution, 'graalvm'))
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.version }}
          cache: 'gradle'
      - uses: graalvm/setup-graalvm@v1
        if: (contains(inputs.distribution, 'graalvm'))
        with:
          version: '22.3.1'
          java-version: ${{ inputs.version }}
          components: 'native-image'
          cache: 'gradle'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Test artifact
        if: (!contains(inputs.compilation, 'aot'))
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: ${{ inputs.directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
      - name: Test artifact in native environment
        if: contains(inputs.compilation, 'aot')
        uses: gradle/gradle-build-action@v2
        with:
          arguments: nativeTest
          build-root-directory: ${{ inputs.directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
